// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKGVX6MuGGbjyxqDYlAA7riDiKlTxVtCs',
    appId: '1:867937670023:web:f75a834cbad9a21849b922',
    messagingSenderId: '867937670023',
    projectId: 'libraryappmanagement',
    authDomain: 'libraryappmanagement.firebaseapp.com',
    storageBucket: 'libraryappmanagement.appspot.com',
    measurementId: 'G-Q7FB4KKNJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8yHrj_JsADG6Q9qtG5h-5EZXVeZZ8c0A',
    appId: '1:867937670023:android:47d5e5c3f6ebd53f49b922',
    messagingSenderId: '867937670023',
    projectId: 'libraryappmanagement',
    storageBucket: 'libraryappmanagement.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBldGM5TvcPe_snm2rqGTvth3k9SymDttE',
    appId: '1:867937670023:ios:19e7e204e369415249b922',
    messagingSenderId: '867937670023',
    projectId: 'libraryappmanagement',
    storageBucket: 'libraryappmanagement.appspot.com',
    iosBundleId: 'com.example.libraryBooksManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBldGM5TvcPe_snm2rqGTvth3k9SymDttE',
    appId: '1:867937670023:ios:474ad4201e7077b349b922',
    messagingSenderId: '867937670023',
    projectId: 'libraryappmanagement',
    storageBucket: 'libraryappmanagement.appspot.com',
    iosBundleId: 'com.example.libraryBooksManagement.RunnerTests',
  );
}
